# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
    binary: lovli

archives:
  - files: ["LICENSE"]

changelog:
  disable: true

docker_digest:
  disable: true

homebrew_casks:
  - homepage: https://github.com/callmesangio/lovli-cli
    description: Use the Lovli URL shortening service in your terminal
    repository:
      owner: callmesangio
      name: homebrew-lovli-cli
    binary: lovli
